apiVersion: apps/v1
kind: Deployment
metadata:
  name: "kubernetes-distributed-deployment"
  namespace: "kube-public"
  labels:
    app: "kubernetes-distributed-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "kubernetes-distributed"
  template:
    metadata:
      labels:
        app: "kubernetes-distributed"
    spec:
      containers:
        - name: info
          image: "registry-1.docker.io/artaneja13/kubernetes-distributed:latest"
          imagePullPolicy: Always
#          resources:
#            requests:
#              memory: "100Mi"
#              cpu: "100m"
#            limits:
#              memory: "120Mi"
#              cpu: "120m"